akron-dotnet-sept-2016-materials/Sample_Code/MVC_SIS/Start/Exercises/Models/Data/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Exercises.Models.Data
{
    public class Student
    {
        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public decimal GPA { get; set; }
        public Address Address { get; set; }
        public Major Major { get; set; }
        public List<Course> Courses { get; set; }
    }
}

akron-dotnet-sept-2016-materials/Sample_Code/MVC_SIS/Start/Exercises/Controllers/StudentController.cs
using Exercises.Models.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Exercises.Models.Data;
using Exercises.Models.ViewModels;

namespace Exercises.Controllers
{
    public class StudentController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult List()
        {
            var model = StudentRepository.GetAll();

            return View(model);
        }

        [HttpGet]
        public ActionResult Add()
        {
            var viewModel = new StudentVM();
            viewModel.SetCourseItems(CourseRepository.GetAll());
            viewModel.SetMajorItems(MajorRepository.GetAll());
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Add(StudentVM studentVM)
        {
            studentVM.Student.Courses = new List<Course>();

            foreach (var id in studentVM.SelectedCourseIds)
                studentVM.Student.Courses.Add(CourseRepository.Get(id));

            studentVM.Student.Major = MajorRepository.Get(studentVM.Student.Major.MajorId);

            StudentRepository.Add(studentVM.Student);

            return RedirectToAction("List");
        }
    }
}

akron-dotnet-sept-2016-materials/Sample_Code/MVC_SIS/Start/Exercises/Views/Student/Add.cshtml
@model Exercises.Models.ViewModels.StudentVM

@{
    ViewBag.Title = "Add";
}

<div class="row">
    <div class="col-xs-12 col-sm-3">
        @Html.Partial("StudentNav")
    </div>
    <div class="col-xs-12 col-sm-9">
        <div class="row">
            <div class="col-xs-12">
                <h3>Add Student</h3>
                <div class="row">
                    @using (Html.BeginForm())
                    {
                        <div class="col-xs-12 col-sm-7">
                            <div class="panel panel-primary">
                                <div class="panel-heading">
                                    <h4 class="panel-title">Personal Details</h4>
                                </div>
                                <div class="panel-body">
                                    <div class="form-group">
                                        <label>First Name:</label>
                                        @Html.TextBoxFor(m => m.Student.FirstName, new { @class = "form-control" })
                                    </div>
                                    <div class="form-group">
                                        <label>Last Name:</label>
                                        @Html.TextBoxFor(m => m.Student.LastName, new { @class = "form-control" })
                                    </div>
                                    <div class="form-group">
                                        <label>Major:</label>
                                        @Html.DropDownListFor(m => m.Student.Major.MajorId, Model.MajorItems, "-Choose One-", new { @class = "form-control" })
                                    </div>
                                    <div class="form-group">
                                        <label>GPA:</label>
                                        @Html.TextBoxFor(m => m.Student.GPA, new { @class = "form-control" })
                                    </div>
                                    <h4>Courses</h4>
                                    <div class="form-group">
                                        @Html.ListBoxFor(m => m.SelectedCourseIds, Model.CourseItems, new { @class = "form-control" })
                                    </div>
                                    <button class="btn btn-primary">Save</button>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

akron-dotnet-sept-2016-materials/Sample_Code/MVC_SIS/Start/Exercises/Views/Student/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-xs-12 col-sm-3">
        @Html.Partial("StudentNav")
    </div>
    <div class="col-xs-12 col-sm-9">
        <p>
            This is the student area of the web site.  We can list, add, edit, and delete student information here.
        </p>
    </div>
</div>

akron-dotnet-sept-2016-materials/Sample_Code/MVC_SIS/Start/Exercises/Views/Student/List.cshtml
@model IEnumerable<Exercises.Models.Data.Student>

@{
    ViewBag.Title = "List";
}

<div class="row">
    <div class="col-xs-12 col-sm-3">
        @Html.Partial("StudentNav")
    </div>
    <div class="col-xs-12 col-sm-9">
        <div class="row">
            <div class="col-xs-12">
                <h4>Student List</h4>
                <p>@Html.ActionLink("Add a Student", "Add", "Student", null, new { @class = "btn btn-primary" })</p>
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Major</th>
                            <th>GPA</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var student in Model)
                        {
                            <tr>
                                <td>@student.FirstName</td>
                                <td>@student.LastName</td>
                                <td>@student.Major.MajorName</td>
                                <td>@student.GPA</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>