akron-dotnet-sept-2016-materials/Sample_Code/MVC_SIS/Start/Exercises/Models/Data/Major.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Exercises.Models.Data
{
    public class Major
    {
        public int MajorId { get; set; }
        public string MajorName { get; set; }
    }
}

akron-dotnet-sept-2016-materials/Sample_Code/MVC_SIS/Start/Exercises/Controllers/AdminController.cs
using Exercises.Models.Data;
using Exercises.Models.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Exercises.Controllers
{
    public class AdminController : Controller
    {

        [HttpGet]
        public ActionResult Majors()
        {
            var model = MajorRepository.GetAll();
            return View(model.ToList());
        }

        [HttpGet]
        public ActionResult AddMajor()
        {
            return View(new Major());
        }

        [HttpPost]
        public ActionResult AddMajor(Major major)
        {
            MajorRepository.Add(major.MajorName);
            return RedirectToAction("Majors");
        }

        [HttpGet]
        public ActionResult EditMajor(int id)
        {
            var major = MajorRepository.Get(id);
            return View(major);
        }

        [HttpPost]
        public ActionResult EditMajor(Major major)
        {
            MajorRepository.Edit(major);
            return RedirectToAction("Majors");
        }

        [HttpGet]
        public ActionResult DeleteMajor(int id)
        {
            var major = MajorRepository.Get(id);
            return View(major);
        }

        [HttpPost]
        public ActionResult DeleteMajor(Major major)
        {
            MajorRepository.Delete(major.MajorId);
            return RedirectToAction("Majors");
        }

    }
}

akron-dotnet-sept-2016-materials/Sample_Code/MVC_SIS/Start/Exercises/Views/Admin/AddMajor.cshtml
@model Exercises.Models.Data.Major

@{
    ViewBag.Title = "Add Major";
}


<div class="row">
    <div class="col-xs-12">
        <h3>Add Major</h3>
        @Html.ActionLink("Return to List", "Majors", "Admin")
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        @using (Html.BeginForm())
        {
            <div class="form-group">
                <label>Major</label>
                @Html.TextBoxFor(m => m.MajorName, new {@class = "form-control", placeholder = "Major"})
            </div>
            <button type="submit" class="btn btn-sm btn-primary">Save</button>
        }
    </div>
</div>      

akron-dotnet-sept-2016-materials/Sample_Code/MVC_SIS/Start/Exercises/Views/Admin/DeleteMajor.cshtml
@model Exercises.Models.Data.Major

@{
    ViewBag.Title = "DeleteMajor";
}

<div class="row">
    <div class="col-xs-12">
        <h3>Delete Major</h3>
        @Html.ActionLink("Return to List", "Majors", "Admin")
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(m => m.MajorId)
            <p>Are you sure that you wish to delete the major @Html.DisplayFor(m => m.MajorName)?</p>
            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
            @Html.ActionLink("Cancel", "Majors", "Admin", null, new {@class="btn btn-sm btn-info"})
        }
    </div>
</div>     

akron-dotnet-sept-2016-materials/Sample_Code/MVC_SIS/Start/Exercises/Views/Admin/EditMajor.cshtml
@model Exercises.Models.Data.Major

@{
    ViewBag.Title = "EditMajor";
}

<div class="row">
    <div class="col-xs-12">
        <h3>Edit Major</h3>
        @Html.ActionLink("Return to List", "Majors", "Admin")
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(m => m.MajorId)
            <div class="form-group">
                <label>Major</label>
                @Html.TextBoxFor(m => m.MajorName, new { @class = "form-control", placeholder = "Major" })
            </div>
            <button type="submit" class="btn btn-sm btn-primary">Save</button>
        }
    </div>
</div>      

akron-dotnet-sept-2016-materials/Sample_Code/MVC_SIS/Start/Exercises/Views/Admin/Majors.cshtml
@model List<Exercises.Models.Data.Major>

@{
    ViewBag.Title = "Majors";
}

<div class="row">
    <div class="col-xs-12">
        <h3>Majors</h3>
        @Html.ActionLink("Add Major", "AddMajor", "Admin", null, new { @class="btn btn-primary"})
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <table class="table table-striped" style="width: auto;">
            <thead>
                <tr>
                    <th>Major</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach(var major in Model)
                {
                    <tr>
                        <td>@major.MajorName</td>
                        <td>
                            @Html.ActionLink("Edit", "EditMajor", "Admin", new { id = major.MajorId }, null) | 
                            @Html.ActionLink("Delete", "DeleteMajor", "Admin", new { id = major.MajorId }, null)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>